FalconTraderWeb/Controllers/LoadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DataAccess.Models;
using DataAccess.Respositories;
using DataAccess.Interfaces;
using DataAccess.Generic;
using Newtonsoft.Json;

namespace FalconTraderWeb.Controllers
{
    public class LoadController : Controller
    {
        private readonly ILoadRepository Repo;
        public LoadController()
        {
            Repo = new LoadRepository();

        }
        public IActionResult Load()
        {
            return View();
        }

        public IActionResult LoadDetails()
        {
            return View();
        }
        [HttpPost]
        public async Task<Result> GetDropDownData()
        {
            var DropDownData = await Repo.GetDropDownData();
            return DropDownData;

        }
        [HttpPost]
        public async Task<Result> SaveLoadInvoice([FromBody]LoadInvoice LoadMaster)
        {
            var Result = await Repo.SaveLoadInvoice(LoadMaster);
            return Result;

        }
        [HttpPost]
        public async Task<Result> UpdateLoadInvoice([FromBody]LoadInvoice LoadMaster)
        {
            var Result = await Repo.UpdateLoadInvoice(LoadMaster);
            return Result;

        }

        [HttpPost]
        public async Task<IActionResult> LoadDetails(DateTime startdate, DateTime enddate)
        {
            var GetLoad = await Repo.GetLoadDetails(startdate, enddate);
            if (GetLoad.Status == ResultStatus.Success)
            {
                return View(GetLoad.Data);
            }
            else
            {
                return View();
            }

        }

        [HttpPost]
        public async Task<JsonResult> LoadEditDetails([FromBody]LoadInvoice LoadInvoice)
        {
            var GetLoad = await Repo.GetLoadByNo(LoadInvoice.LoadInvoiceNo);

            string json = JsonConvert.SerializeObject(GetLoad);
            return Json(json);

        }


    }
}

FalconTraderWeb/Views/Load/LoadDetails.cshtml
@{
    ViewData["Title"] = "LoadDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>LoadDetails</h1>
@using DataAccess.Models
@model List<LoadModel>

@section Scripts {
    <!-- Include view-specific JavaScript files -->
    <script src="~/js/Custom/Load.js"></script>
}
<!-- ============================================================== -->
<div class="main-content">
    <div>
        <div class="container-fluid">
            <!-- start page title -->
            <!-- end page title -->
            <!-- <div class="col-xl-12"> -->
            <div class="card">
                <div class="card-header align-items-center d-flex">

                    <div class="flex-shrink-0">
                        <ul class="nav nav-tabs-custom card-header-tabs" role="tablist">
                            <li class="nav-item">
                                <a class="nav-link active" data-bs-toggle="tab" href="#DailyReport" role="tab">Load Details</a>
                            </li>


                        </ul>
                    </div>

                </div><!-- end card header -->
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="LoadReport" role="tabpanel">

                            <form asp-controller="Load" asp-action="LoadDetails" method="post">

                                <div>
                                    <div class="row">

                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group mb-3">
                                                <div>
                                                    <label class="form-label">Select From Date Range</label>
                                                    @*<input type="text" class="form-control" name="datepicker" id="datepicker">*@
                                                    <input type="date" name="startdate" class="form-control" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-6">
                                            <div class="form-group mb-3">
                                                <div>
                                                    <label class="form-label">Select To Date Range</label>
                                                    @*<input type="text" class="form-control" name="datepicker" id="datepicker">*@
                                                    <input type="date" name="enddate" class="form-control" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col-lg-4 col-md-6">
                                            <div class="text-center">
                                                <button type="submit" class="btn btn-success w-md">Search</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </form>
                            <div class="row">
                                <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h4 class="card-title">Report</h4>
                                            @*<input type="hidden" value="@ViewBag.StockIn" id="allsalestab" />*@
                                        </div>
                                        <div class="card-body">

                                            <table id="LoadTable" class="table table-hover table-responsive table-striped table-bordered table-condensed dataTable-excel datatable">
                                                <thead>
                                                    <tr>
                                                        <th>Load Invoice No</th>
                                                        <th>Route Name</th>
                                                        <th>BookerName</th>
                                                        <th>Delivery Man</th>
                                                        <th>Vehicle No</th>
                                                        <th>Product Name</th>
                                                        <th>Quantity</th>
                                                        <th>Return</th>
                                                        <th>Invoice Entry Date</th>
                                                        <th>Load Date</th>

                                                    </tr>
                                                </thead>

                                                @if (Model != null)
                                                {
                                                    <tbody>

                                                        @foreach (var Load in Model)
                                                        {
                                                            <tr id="row">
                                                                <td>@Load.LoadInvoiceNo</td>
                                                                <td>@Load.RouteName</td>
                                                                <td>@Load.BookerName</td>
                                                                <td>@Load.DeliveryMan</td>
                                                                <td>@Load.VehicleNo</td>
                                                                <td>@Load.ProductName</td>
                                                                <td>@Load.Quantity</td>
                                                                <td>@Load.Return</td>
                                                                <td>@Load.Date</td>
                                                                <td>@Load.LoadDate</td>

                                                            </tr>
                                                        }

                                                    </tbody>

                                                    <tfoot>
                                                        <tr>
                                                            <th colspan="6"></th>

                                                            <th><span>@Model.Sum(i => i.Quantity)</span> </th>


                                                        </tr>
                                                    </tfoot>
                                                }
                                            </table>
                                            @*<div class="row" style="margin-top:40px">
                                                @if (Model != null)
                                                {
                                                    <div class="col-lg-4 col-md-6">
                                                        <h5 class="font-size-14 mb-4">Total</h5>
                                                    </div>

                                                    <div class="col-lg-4 col-md-6">
                                                        <h5 class="font-size-14 mb-4">Total Tax Amount </h5>
                                                    </div>
                                                    <div class="col-lg-4 col-md-6">
                                                        <h5 class="font-size-14 mb-4">Total Discount Amount </h5>
                                                    </div>

                                                    @*<div class="col-lg-4 col-md-6">
                                                        <h5 class="font-size-14 mb-4">
                                                            Crates Sold
                                                            <span>
                                                                @Model.SelectMany(i => i.SaleInvoiceDetail).Sum(detail => Convert.ToInt32(detail.Quantity))

                                                            </span>
                                                        </h5>
                                                    </div>*@

                                        </div>
                                    </div>
                                </div>
                            </div> <!-- end col -->
                        </div> <!-- end row -->

                    </div>



                    <!-- end tab pane -->
                </div>
                <!-- end tab content -->
            </div>

            <!-- end card body -->
        </div>
        <!-- end card -->
        <!-- end col -->
    </div>
    <!-- end row -->
    <!-- end row -->
    <!-- end row -->

</div> <!-- container-fluid -->
<!-- End Page-content -->
<!-- JAVASCRIPT -->